# The manual about all configuration options is here:
#   https://github.com/crate-ci/typos/blob/master/docs/reference.md

[default]
check-file = true
check-filename = true
extend-ignore-re = [
    # NOTE Allow to mark block of text to exclude from spellchecking inside C++ or hash-style comments (CMake,Python,&etc.)
    "(?s)(#|//)\\s*(NOQA|noqa):? spellcheck(: *|=| +)off.*?\\n\\s*(#|//)\\s*(NOQA|noqa):? spellcheck(: *|=| +)on"
    # NOTE Allow to mark a line to exclude from spellchecking
  , "(?Rm)^.*(#|//)\\s*(NOQA|noqa):? spellcheck(: *|=| +)disable-line$"
    # NOTE Stop checking from this line to the end of file
    # This line is a marker added by Git to the `COMMIT_EDITMSG`.
  , "(?sm)^# ------------------------ >8 ------------------------$.*"
  ]
locale = "en-us"
# ATTENTION If, for any reason, you want to add the
# `extend-ignore-identifiers-re` to this section,
# please also modify the `.gitlab/ci/typos.bash`
# script accordingly.
#extend-ignore-identifiers-re=["\\b[0-9a-f]{10}\\b"]

# Add repo-wide false positives here in the form of `word = "word"`.
# Check the manual for details.
[default.extend-words]
HPE = "HPE"
# British spelling of `XCODE_SCHEME_UNDEFINED_BEHAVIOUR_SANITIZER` property name.
BEHAVIOUR = "BEHAVIOUR"
# Misspelled `Fortran_BUILDING_INSTRINSIC_MODULES` property name kept for compatibility: `INSTRINSIC` should be `INTRINSIC`.
INSTRINSIC = "INSTRINSIC"
# This is a file extension for `cobertura-merge`
ser = "ser"
# The Ninja option name
restat = "restat"
# SpectreMitigation
Spectre = "Spectre"
# Identifier used in source code (`GlobalTargetInfo`)
gti = "gti"

[files]
ignore-hidden = false
ignore-dot = false
extend-exclude = [
    "CONTRIBUTORS.rst"
    # Exclude third-party sources.
  , "Source/CursesDialog/form/"
  , "Source/kwsys/"
  , "Source/bindexplib.cxx"
  , "Source/cmcldeps.cxx"
  , "Source/QtDialog/*.ui"
  , "Utilities/cm*"
  , "Utilities/ClangTidyModule"
  , "Utilities/KWIML"
    # FIXME: Fix spelling typos in tests.  Exclude for now.
  , "Tests"
  ]

# BEGIN Type-specific settings
[type.cmake.extend-identifiers]
COMMANDs = "COMMANDs"
xCOMMANDx = "xCOMMANDx"
TYPEs = "TYPEs"

[type.cmake.extend-words]
# Some compiler's options trigger false-positives
Fo = "Fo"
ot = "ot"
# Part of compiler executable name, e.g., `arm-unknown-nto-qnx6`, but also could be in a literal string.
nto = "nto"

[type.cpp.extend-identifiers]
APPENDed = "APPENDed"

[type.json.extend-identifiers]
# Some compiler options from `Templates/MSBuild/FlagTables/*.json` trigger too many false-positives.
Fo = "Fo"
fo = "fo"
Ot = "Ot"
SEH = "SEH"

[type.py.extend-identifiers]
typ = "typ"

[type.rst]
extend-ignore-re = [
    # NOTE Allow to mark block of text to exclude from spellchecking as RST comments
    "(?s)\\.\\.\\s+(NOQA|noqa):? spellcheck(: *|=| +)off.*?\\n\\.\\.\\s+(NOQA|noqa):? spellcheck(: *|=| +)on"
  ]
# END Type-specific settings
